version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    extra_hosts:
      - "deb.debian.org:151.101.0.204"
      - "security.debian.org:151.101.0.204"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: interactive_dashboard
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # MailHog web interface
      - "1025:1025" # MailHog SMTP server
  vueapp:
    build:
      context: ./frontend
      dockerfile: docker/vue/Dockerfile
    ports:
      - "8080:8080" # Expose Vue.js app on port 8080
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - app
volumes:
  dbdata:
